package Interfaz;

import adapter.Edad;
import adapter.EdadAdapter;
import Entradas.InputMascota;
import Salidas.OutputMascota;
import factory.ConsoleMascotaFactory;
import factory.JOptionMascotaFactory;
import factory.MascotaFactory;
import factory.WebMascotaFactory;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu- formulario de mascotas");
        
    }
    
    private void ejecutarProceso(MascotaFactory factory) {

    InputMascota input = factory.crearInput();
    OutputMascota output = factory.crearOutput();

    String tipo = input.pedirTipoMascota();
    String nombre = input.pedirNombreMascota();

    String edadTexto = input.pedriEdadMascota();

    Edad edad = new EdadAdapter(edadTexto);

    output.mostrarMascota(tipo, nombre, edad.getEdad());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonConsola = new javax.swing.JButton();
        BotonJOptionpane = new javax.swing.JButton();
        BotonWEB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Bienvenido(@) ");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 17, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("por favor selecciona donde registrar tus datos");
        jLabel2.setFocusTraversalPolicyProvider(true);
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 310, 40));

        BotonConsola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonConsola.setForeground(new java.awt.Color(0, 0, 204));
        BotonConsola.setText("En Consola");
        BotonConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsolaActionPerformed(evt);
            }
        });
        jPanel1.add(BotonConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        BotonJOptionpane.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonJOptionpane.setForeground(new java.awt.Color(0, 0, 204));
        BotonJOptionpane.setText("En JOptionpane");
        BotonJOptionpane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJOptionpaneActionPerformed(evt);
            }
        });
        jPanel1.add(BotonJOptionpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        BotonWEB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonWEB.setForeground(new java.awt.Color(0, 0, 204));
        BotonWEB.setText("En WEB");
        BotonWEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonWEBActionPerformed(evt);
            }
        });
        jPanel1.add(BotonWEB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        BotonSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(0, 0, 255));
        BotonSalir.setText("SALIR");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonSalir)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 300));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsolaActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(this,"Yendo a Consola", "CONSOLA",JOptionPane.INFORMATION_MESSAGE);
        ejecutarProceso(new ConsoleMascotaFactory());
        JOptionPane.showMessageDialog(this,"Regresando a Menu", "MEnu",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(true);
    }//GEN-LAST:event_BotonConsolaActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonJOptionpaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJOptionpaneActionPerformed
         ejecutarProceso(new JOptionMascotaFactory());
    }//GEN-LAST:event_BotonJOptionpaneActionPerformed

    private void BotonWEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonWEBActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(this,"yendo a la web", "WEB",JOptionPane.INFORMATION_MESSAGE);
        ejecutarProceso(new WebMascotaFactory());
        this.setVisible(true);
    }//GEN-LAST:event_BotonWEBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsola;
    private javax.swing.JButton BotonJOptionpane;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonWEB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
